//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockManagement.Language {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Feedback {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Feedback() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StockManagement.Language.Feedback.Feedback", typeof(Feedback).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string feedback {
            get {
                return ResourceManager.GetString("feedback", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Report a problem.
        /// </summary>
        public static string reportProblem {
            get {
                return ResourceManager.GetString("reportProblem", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string feedbackCategory {
            get {
                return ResourceManager.GetString("feedbackCategory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string feedbackCategoryFeedback {
            get {
                return ResourceManager.GetString("feedbackCategoryFeedback", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bug.
        /// </summary>
        public static string feedbackCategoryBug {
            get {
                return ResourceManager.GetString("feedbackCategoryBug", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string feedbackMessage {
            get {
                return ResourceManager.GetString("feedbackMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to What happened?.
        /// </summary>
        public static string feedbackMessagePlaceholder {
            get {
                return ResourceManager.GetString("feedbackMessagePlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Message is required..
        /// </summary>
        public static string feedbackMessageRequired {
            get {
                return ResourceManager.GetString("feedbackMessageRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Thanks - sent..
        /// </summary>
        public static string feedbackSent {
            get {
                return ResourceManager.GetString("feedbackSent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Couldn't send. Try again later..
        /// </summary>
        public static string feedbackSendFailed {
            get {
                return ResourceManager.GetString("feedbackSendFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Something went wrong..
        /// </summary>
        public static string errorOccurred {
            get {
                return ResourceManager.GetString("errorOccurred", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Send error report?.
        /// </summary>
        public static string sendErrorReport {
            get {
                return ResourceManager.GetString("sendErrorReport", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Don't send.
        /// </summary>
        public static string dontSend {
            get {
                return ResourceManager.GetString("dontSend", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string send {
            get {
                return ResourceManager.GetString("send", resourceCulture);
            }
        }
    }
}
