//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockManagement.Language {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CashRegister {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CashRegister() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StockManagement.Language.CashRegister.CashRegister", typeof(CashRegister).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cash Register.
        /// </summary>
        public static string cashRegister {
            get {
                return ResourceManager.GetString("cashRegister", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cash Register Sessions.
        /// </summary>
        public static string cashRegisterSessions {
            get {
                return ResourceManager.GetString("cashRegisterSessions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open Session.
        /// </summary>
        public static string openSession {
            get {
                return ResourceManager.GetString("openSession", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Close Session.
        /// </summary>
        public static string closeSession {
            get {
                return ResourceManager.GetString("closeSession", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Opening Float.
        /// </summary>
        public static string openingFloat {
            get {
                return ResourceManager.GetString("openingFloat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Counted Amount.
        /// </summary>
        public static string countedAmount {
            get {
                return ResourceManager.GetString("countedAmount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Expected Amount.
        /// </summary>
        public static string expectedAmount {
            get {
                return ResourceManager.GetString("expectedAmount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Difference.
        /// </summary>
        public static string difference {
            get {
                return ResourceManager.GetString("difference", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cash In.
        /// </summary>
        public static string cashIn {
            get {
                return ResourceManager.GetString("cashIn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cash Out.
        /// </summary>
        public static string cashOut {
            get {
                return ResourceManager.GetString("cashOut", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string amount {
            get {
                return ResourceManager.GetString("amount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add Movement.
        /// </summary>
        public static string addMovement {
            get {
                return ResourceManager.GetString("addMovement", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string movementType {
            get {
                return ResourceManager.GetString("movementType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Opened At.
        /// </summary>
        public static string openedAt {
            get {
                return ResourceManager.GetString("openedAt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Closed At.
        /// </summary>
        public static string closedAt {
            get {
                return ResourceManager.GetString("closedAt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Opened By.
        /// </summary>
        public static string openedBy {
            get {
                return ResourceManager.GetString("openedBy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Closed By.
        /// </summary>
        public static string closedBy {
            get {
                return ResourceManager.GetString("closedBy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string note {
            get {
                return ResourceManager.GetString("note", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Movements.
        /// </summary>
        public static string movements {
            get {
                return ResourceManager.GetString("movements", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No session is open..
        /// </summary>
        public static string noOpenSession {
            get {
                return ResourceManager.GetString("noOpenSession", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A session is already open..
        /// </summary>
        public static string cashRegisterSessionAlreadyOpen {
            get {
                return ResourceManager.GetString("cashRegisterSessionAlreadyOpen", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Opening float must not be negative..
        /// </summary>
        public static string invalidOpeningFloat {
            get {
                return ResourceManager.GetString("invalidOpeningFloat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Counted amount must not be negative..
        /// </summary>
        public static string negativeCountedAmount {
            get {
                return ResourceManager.GetString("negativeCountedAmount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Close-out report.
        /// </summary>
        public static string closeOutReport {
            get {
                return ResourceManager.GetString("closeOutReport", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string statusOpen {
            get {
                return ResourceManager.GetString("statusOpen", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        public static string statusClosed {
            get {
                return ResourceManager.GetString("statusClosed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string viewDetails {
            get {
                return ResourceManager.GetString("viewDetails", resourceCulture);
            }
        }
    }
}
