//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockManagement.Language {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RemissionNotes {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RemissionNotes() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StockManagement.Language.RemissionNotes.RemissionNotes", typeof(RemissionNotes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remission Notes.
        /// </summary>
        public static string remissionNotes {
            get {
                return ResourceManager.GetString("remissionNotes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remission Note.
        /// </summary>
        public static string remissionNote {
            get {
                return ResourceManager.GetString("remissionNote", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Create Remission Note.
        /// </summary>
        public static string createRemissionNote {
            get {
                return ResourceManager.GetString("createRemissionNote", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remission note {0} saved..
        /// </summary>
        public static string remissionNoteSavedToast {
            get {
                return ResourceManager.GetString("remissionNoteSavedToast", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Destination Address.
        /// </summary>
        public static string destinationAddress {
            get {
                return ResourceManager.GetString("destinationAddress", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Destination address is required..
        /// </summary>
        public static string destinationAddressRequired {
            get {
                return ResourceManager.GetString("destinationAddressRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reason is invalid..
        /// </summary>
        public static string reasonInvalid {
            get {
                return ResourceManager.GetString("reasonInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sale.
        /// </summary>
        public static string reasonVenta {
            get {
                return ResourceManager.GetString("reasonVenta", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Consignment.
        /// </summary>
        public static string reasonConsignacion {
            get {
                return ResourceManager.GetString("reasonConsignacion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Replacement.
        /// </summary>
        public static string reasonReposicion {
            get {
                return ResourceManager.GetString("reasonReposicion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Transfer Between Premises.
        /// </summary>
        public static string reasonTrasladoEntreLocales {
            get {
                return ResourceManager.GetString("reasonTrasladoEntreLocales", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string reasonOtro {
            get {
                return ResourceManager.GetString("reasonOtro", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string remissionNoteNumber {
            get {
                return ResourceManager.GetString("remissionNoteNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string remissionNoteDate {
            get {
                return ResourceManager.GetString("remissionNoteDate", resourceCulture);
            }
        }
    }
}
