//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockManagement.Language {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Settings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Settings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StockManagement.Language.Settings.Settings", typeof(Settings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Adjust size of border for inner window.
        /// </summary>
        public static string adjustDialogBorderSize {
            get {
                return ResourceManager.GetString("adjustDialogBorderSize", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string english {
            get {
                return ResourceManager.GetString("english", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Deutsch.
        /// </summary>
        public static string german {
            get {
                return ResourceManager.GetString("german", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to For language changes to take effect, please restart the application..
        /// </summary>
        public static string languageChangedMessage {
            get {
                return ResourceManager.GetString("languageChangedMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select language:.
        /// </summary>
        public static string selectLanguage {
            get {
                return ResourceManager.GetString("selectLanguage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Español.
        /// </summary>
        public static string spanish {
            get {
                return ResourceManager.GetString("spanish", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Company settings.
        /// </summary>
        public static string companySettings {
            get {
                return ResourceManager.GetString("companySettings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Company name.
        /// </summary>
        public static string companyName {
            get {
                return ResourceManager.GetString("companyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tax ID.
        /// </summary>
        public static string taxId {
            get {
                return ResourceManager.GetString("taxId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string currency {
            get {
                return ResourceManager.GetString("currency", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to VAT rate (%).
        /// </summary>
        public static string vatRate {
            get {
                return ResourceManager.GetString("vatRate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Payment term (days).
        /// </summary>
        public static string paymentTermInDays {
            get {
                return ResourceManager.GetString("paymentTermInDays", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to First invoice number.
        /// </summary>
        public static string firstInvoiceNumber {
            get {
                return ResourceManager.GetString("firstInvoiceNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to First customer id.
        /// </summary>
        public static string firstCustomerId {
            get {
                return ResourceManager.GetString("firstCustomerId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Currency decimal digits.
        /// </summary>
        public static string currencyDecimalDigits {
            get {
                return ResourceManager.GetString("currencyDecimalDigits", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to VAT rate must be between 0 and 100...
        /// </summary>
        public static string vatRateOutOfRange {
            get {
                return ResourceManager.GetString("vatRateOutOfRange", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Payment term cannot be negative...
        /// </summary>
        public static string paymentTermNegative {
            get {
                return ResourceManager.GetString("paymentTermNegative", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to First invoice number must be greater than zero...
        /// </summary>
        public static string firstInvoiceNumberNotPositive {
            get {
                return ResourceManager.GetString("firstInvoiceNumberNotPositive", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to First customer id must be greater than zero...
        /// </summary>
        public static string firstCustomerIdNotPositive {
            get {
                return ResourceManager.GetString("firstCustomerIdNotPositive", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Currency decimal digits must be between 0 and 4...
        /// </summary>
        public static string currencyDecimalDigitsOutOfRange {
            get {
                return ResourceManager.GetString("currencyDecimalDigitsOutOfRange", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to RUC.
        /// </summary>
        public static string ruc {
            get {
                return ResourceManager.GetString("ruc", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Timbrado number.
        /// </summary>
        public static string timbradoNumber {
            get {
                return ResourceManager.GetString("timbradoNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Timbrado valid from.
        /// </summary>
        public static string timbradoValidFrom {
            get {
                return ResourceManager.GetString("timbradoValidFrom", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Timbrado valid to.
        /// </summary>
        public static string timbradoValidTo {
            get {
                return ResourceManager.GetString("timbradoValidTo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Establishment code.
        /// </summary>
        public static string establishmentCode {
            get {
                return ResourceManager.GetString("establishmentCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Point of sale code.
        /// </summary>
        public static string pointOfSaleCode {
            get {
                return ResourceManager.GetString("pointOfSaleCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to RUC check digit is invalid...
        /// </summary>
        public static string rucInvalid {
            get {
                return ResourceManager.GetString("rucInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Establishment code must be 3 digits...
        /// </summary>
        public static string establishmentCodeInvalid {
            get {
                return ResourceManager.GetString("establishmentCodeInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Point of sale code must be 3 digits...
        /// </summary>
        public static string pointOfSaleCodeInvalid {
            get {
                return ResourceManager.GetString("pointOfSaleCodeInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Timbrado valid-to date cannot be before valid-from...
        /// </summary>
        public static string timbradoDateRangeInvalid {
            get {
                return ResourceManager.GetString("timbradoDateRangeInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Printer settings...
        /// </summary>
        public static string printerSettings {
            get {
                return ResourceManager.GetString("printerSettings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Default printer name...
        /// </summary>
        public static string defaultPrinterName {
            get {
                return ResourceManager.GetString("defaultPrinterName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Receipt paper width (mm)...
        /// </summary>
        public static string receiptPaperWidthMm {
            get {
                return ResourceManager.GetString("receiptPaperWidthMm", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to KuDE format...
        /// </summary>
        public static string kudeFormat {
            get {
                return ResourceManager.GetString("kudeFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ticket...
        /// </summary>
        public static string ticket {
            get {
                return ResourceManager.GetString("ticket", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A4...
        /// </summary>
        public static string a4 {
            get {
                return ResourceManager.GetString("a4", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Print receipt automatically after sale...
        /// </summary>
        public static string printOnSaleComplete {
            get {
                return ResourceManager.GetString("printOnSaleComplete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Print test page...
        /// </summary>
        public static string printTestPage {
            get {
                return ResourceManager.GetString("printTestPage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Receipt paper width must be between 20 and 300 mm...
        /// </summary>
        public static string receiptPaperWidthMmOutOfRange {
            get {
                return ResourceManager.GetString("receiptPaperWidthMmOutOfRange", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Backups.
        /// </summary>
        public static string backups {
            get {
                return ResourceManager.GetString("backups", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Create backup.
        /// </summary>
        public static string createBackup {
            get {
                return ResourceManager.GetString("createBackup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No backups yet.
        /// </summary>
        public static string noBackupsYet {
            get {
                return ResourceManager.GetString("noBackupsYet", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string backupDate {
            get {
                return ResourceManager.GetString("backupDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string backupSize {
            get {
                return ResourceManager.GetString("backupSize", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string download {
            get {
                return ResourceManager.GetString("download", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Restore from file.
        /// </summary>
        public static string restoreBackup {
            get {
                return ResourceManager.GetString("restoreBackup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Restoring replaces all current data with the backup's...
        /// </summary>
        public static string restoreWarning {
            get {
                return ResourceManager.GetString("restoreWarning", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to I understand this will overwrite all current data.
        /// </summary>
        public static string restoreConfirmCheckbox {
            get {
                return ResourceManager.GetString("restoreConfirmCheckbox", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string restore {
            get {
                return ResourceManager.GetString("restore", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Backup created.
        /// </summary>
        public static string backupCreatedToast {
            get {
                return ResourceManager.GetString("backupCreatedToast", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Restore complete. Restart the app now...
        /// </summary>
        public static string restoreSucceededMessage {
            get {
                return ResourceManager.GetString("restoreSucceededMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You must confirm before restoring...
        /// </summary>
        public static string confirmRequired {
            get {
                return ResourceManager.GetString("confirmRequired", resourceCulture);
            }
        }
    }
}
