//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockManagement.Language {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Invoices {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Invoices() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StockManagement.Language.Invoices.Invoices", typeof(Invoices).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add to Shopping Cart.
        /// </summary>
        public static string addToShoppingCart {
            get {
                return ResourceManager.GetString("addToShoppingCart", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bar.
        /// </summary>
        public static string cash {
            get {
                return ResourceManager.GetString("cash", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel invoice.
        /// </summary>
        public static string cancelInvoice {
            get {
                return ResourceManager.GetString("cancelInvoice", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string cancelled {
            get {
                return ResourceManager.GetString("cancelled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancellation reason.
        /// </summary>
        public static string cancelReason {
            get {
                return ResourceManager.GetString("cancelReason", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Erstellungsdatum.
        /// </summary>
        public static string creationDate {
            get {
                return ResourceManager.GetString("creationDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Kredit.
        /// </summary>
        public static string credit {
            get {
                return ResourceManager.GetString("credit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Die Anzahl der verkauften Artikel ist zu hoch. (Unzureichende Artikel auf Lager).
        /// </summary>
        public static string exceptionShoppingCartItemOutOfRange {
            get {
                return ResourceManager.GetString("exceptionShoppingCartItemOutOfRange", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ablaufsdatum.
        /// </summary>
        public static string expirationDate {
            get {
                return ResourceManager.GetString("expirationDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CDC.
        /// </summary>
        public static string cdc {
            get {
                return ResourceManager.GetString("cdc", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SIFEN status.
        /// </summary>
        public static string transmissionStatus {
            get {
                return ResourceManager.GetString("transmissionStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Credit Note.
        /// </summary>
        public static string creditNote {
            get {
                return ResourceManager.GetString("creditNote", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Credit Note ID.
        /// </summary>
        public static string creditNoteId {
            get {
                return ResourceManager.GetString("creditNoteId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Not enough in stock, only available:.
        /// </summary>
        public static string insufficientStock {
            get {
                return ResourceManager.GetString("insufficientStock", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The payment amount must be greater than zero..
        /// </summary>
        public static string invalidPaymentAmount {
            get {
                return ResourceManager.GetString("invalidPaymentAmount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Rechnung.
        /// </summary>
        public static string invoice {
            get {
                return ResourceManager.GetString("invoice", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invoice ID.
        /// </summary>
        public static string invoiceId {
            get {
                return ResourceManager.GetString("invoiceId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invoice not found..
        /// </summary>
        public static string invoiceNotFound {
            get {
                return ResourceManager.GetString("invoiceNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invoices.
        /// </summary>
        public static string invoices {
            get {
                return ResourceManager.GetString("invoices", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New sale.
        /// </summary>
        public static string newSale {
            get {
                return ResourceManager.GetString("newSale", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The payment amount exceeds the invoice's amount due..
        /// </summary>
        public static string paymentExceedsAmountDue {
            get {
                return ResourceManager.GetString("paymentExceedsAmountDue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Verkaufsbedingung.
        /// </summary>
        public static string saleCondition {
            get {
                return ResourceManager.GetString("saleCondition", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search in dates:.
        /// </summary>
        public static string searchDates {
            get {
                return ResourceManager.GetString("searchDates", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search Invoice IDs:.
        /// </summary>
        public static string searchInvoiceIds {
            get {
                return ResourceManager.GetString("searchInvoiceIds", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sell.
        /// </summary>
        public static string sell {
            get {
                return ResourceManager.GetString("sell", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Shopping Cart.
        /// </summary>
        public static string shoppingCart {
            get {
                return ResourceManager.GetString("shoppingCart", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Shopping Cart Items.
        /// </summary>
        public static string shoppingCartItems {
            get {
                return ResourceManager.GetString("shoppingCartItems", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Steuer.
        /// </summary>
        public static string tax {
            get {
                return ResourceManager.GetString("tax", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string total {
            get {
                return ResourceManager.GetString("total", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Sale condition is invalid...
        /// </summary>
        public static string saleConditionInvalid {
            get {
                return ResourceManager.GetString("saleConditionInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to At least one item is required...
        /// </summary>
        public static string saleItemsRequired {
            get {
                return ResourceManager.GetString("saleItemsRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Payment method is invalid...
        /// </summary>
        public static string paymentMethodInvalid {
            get {
                return ResourceManager.GetString("paymentMethodInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string statusPending {
            get {
                return ResourceManager.GetString("statusPending", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Paid.
        /// </summary>
        public static string statusPaid {
            get {
                return ResourceManager.GetString("statusPaid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Overdue.
        /// </summary>
        public static string statusOverdue {
            get {
                return ResourceManager.GetString("statusOverdue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invoice {0} saved..
        /// </summary>
        public static string invoiceSavedToast {
            get {
                return ResourceManager.GetString("invoiceSavedToast", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Payment link.
        /// </summary>
        public static string paymentLink {
            get {
                return ResourceManager.GetString("paymentLink", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Generate payment link.
        /// </summary>
        public static string generatePaymentLink {
            get {
                return ResourceManager.GetString("generatePaymentLink", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string paymentLinkAmount {
            get {
                return ResourceManager.GetString("paymentLinkAmount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string paymentLinkCreated {
            get {
                return ResourceManager.GetString("paymentLinkCreated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Expires.
        /// </summary>
        public static string paymentLinkExpires {
            get {
                return ResourceManager.GetString("paymentLinkExpires", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open payment page.
        /// </summary>
        public static string paymentLinkOpen {
            get {
                return ResourceManager.GetString("paymentLinkOpen", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Expired.
        /// </summary>
        public static string statusExpired {
            get {
                return ResourceManager.GetString("statusExpired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string statusFailed {
            get {
                return ResourceManager.GetString("statusFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invoice is already paid..
        /// </summary>
        public static string invoiceAlreadyPaid {
            get {
                return ResourceManager.GetString("invoiceAlreadyPaid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Payment gateway error. Try again..
        /// </summary>
        public static string paymentLinkGatewayError {
            get {
                return ResourceManager.GetString("paymentLinkGatewayError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Marangatu export.
        /// </summary>
        public static string marangatuExport {
            get {
                return ResourceManager.GetString("marangatuExport", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Download CSV.
        /// </summary>
        public static string downloadIvaBook {
            get {
                return ResourceManager.GetString("downloadIvaBook", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to View KuDE.
        /// </summary>
        public static string viewKude {
            get {
                return ResourceManager.GetString("viewKude", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to KuDE not available yet..
        /// </summary>
        public static string kudeUnavailable {
            get {
                return ResourceManager.GetString("kudeUnavailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Credit notes.
        /// </summary>
        public static string creditNotes {
            get {
                return ResourceManager.GetString("creditNotes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Debit notes.
        /// </summary>
        public static string debitNotes {
            get {
                return ResourceManager.GetString("debitNotes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Debit note.
        /// </summary>
        public static string debitNote {
            get {
                return ResourceManager.GetString("debitNote", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New debit note.
        /// </summary>
        public static string newDebitNote {
            get {
                return ResourceManager.GetString("newDebitNote", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        public static string items {
            get {
                return ResourceManager.GetString("items", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add item.
        /// </summary>
        public static string addItem {
            get {
                return ResourceManager.GetString("addItem", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Debit note {0} saved..
        /// </summary>
        public static string debitNoteSavedToast {
            get {
                return ResourceManager.GetString("debitNoteSavedToast", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SIFEN operations.
        /// </summary>
        public static string sifenOperations {
            get {
                return ResourceManager.GetString("sifenOperations", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Contingency.
        /// </summary>
        public static string contingencyTab {
            get {
                return ResourceManager.GetString("contingencyTab", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancellation.
        /// </summary>
        public static string cancellationTab {
            get {
                return ResourceManager.GetString("cancellationTab", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Number void.
        /// </summary>
        public static string numberVoidTab {
            get {
                return ResourceManager.GetString("numberVoidTab", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Stuck transmissions.
        /// </summary>
        public static string stuckTransmissionsTab {
            get {
                return ResourceManager.GetString("stuckTransmissionsTab", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Range configured.
        /// </summary>
        public static string contingencyRangeConfigured {
            get {
                return ResourceManager.GetString("contingencyRangeConfigured", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Range start.
        /// </summary>
        public static string rangeStart {
            get {
                return ResourceManager.GetString("rangeStart", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Range end.
        /// </summary>
        public static string rangeEnd {
            get {
                return ResourceManager.GetString("rangeEnd", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Next number.
        /// </summary>
        public static string contingencyNextNumber {
            get {
                return ResourceManager.GetString("contingencyNextNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remaining.
        /// </summary>
        public static string contingencyRemaining {
            get {
                return ResourceManager.GetString("contingencyRemaining", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enable contingency mode.
        /// </summary>
        public static string enableContingencyMode {
            get {
                return ResourceManager.GetString("enableContingencyMode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Disable contingency mode.
        /// </summary>
        public static string disableContingencyMode {
            get {
                return ResourceManager.GetString("disableContingencyMode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save range.
        /// </summary>
        public static string saveRange {
            get {
                return ResourceManager.GetString("saveRange", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Request cancellation.
        /// </summary>
        public static string requestCancellation {
            get {
                return ResourceManager.GetString("requestCancellation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invoice number.
        /// </summary>
        public static string invoiceNumber {
            get {
                return ResourceManager.GetString("invoiceNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Requested at.
        /// </summary>
        public static string requestedAt {
            get {
                return ResourceManager.GetString("requestedAt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Request number void.
        /// </summary>
        public static string requestNumberVoid {
            get {
                return ResourceManager.GetString("requestNumberVoid", resourceCulture);
            }
        }
    }
}
