//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockManagement.Language {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Licensing {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Licensing() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StockManagement.Language.Licensing.Licensing", typeof(Licensing).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        public static string licensing {
            get {
                return ResourceManager.GetString("licensing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        public static string licenseStatus {
            get {
                return ResourceManager.GetString("licenseStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        public static string licenseStatusTrial {
            get {
                return ResourceManager.GetString("licenseStatusTrial", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        public static string licenseStatusActive {
            get {
                return ResourceManager.GetString("licenseStatusActive", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        public static string licenseStatusGracePeriod {
            get {
                return ResourceManager.GetString("licenseStatusGracePeriod", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        public static string licenseStatusLocked {
            get {
                return ResourceManager.GetString("licenseStatusLocked", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        public static string daysRemaining {
            get {
                return ResourceManager.GetString("daysRemaining", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        public static string currentPlan {
            get {
                return ResourceManager.GetString("currentPlan", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        public static string subscriptionExpiresOn {
            get {
                return ResourceManager.GetString("subscriptionExpiresOn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        public static string monthlyPlan {
            get {
                return ResourceManager.GetString("monthlyPlan", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        public static string yearlyPlan {
            get {
                return ResourceManager.GetString("yearlyPlan", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        public static string noPlan {
            get {
                return ResourceManager.GetString("noPlan", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        public static string monthlyPrice {
            get {
                return ResourceManager.GetString("monthlyPrice", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        public static string yearlyPrice {
            get {
                return ResourceManager.GetString("yearlyPrice", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        public static string licenseKey {
            get {
                return ResourceManager.GetString("licenseKey", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        public static string activateLicense {
            get {
                return ResourceManager.GetString("activateLicense", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        public static string activate {
            get {
                return ResourceManager.GetString("activate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        public static string licenseKeyRequired {
            get {
                return ResourceManager.GetString("licenseKeyRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        public static string licenseKeyInvalid {
            get {
                return ResourceManager.GetString("licenseKeyInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        public static string licenseActivated {
            get {
                return ResourceManager.GetString("licenseActivated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        public static string trialBannerMessage {
            get {
                return ResourceManager.GetString("trialBannerMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        public static string graceBannerMessage {
            get {
                return ResourceManager.GetString("graceBannerMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        public static string licenseLockedTitle {
            get {
                return ResourceManager.GetString("licenseLockedTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        public static string licenseLockedMessage {
            get {
                return ResourceManager.GetString("licenseLockedMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        public static string contactToSubscribe {
            get {
                return ResourceManager.GetString("contactToSubscribe", resourceCulture);
            }
        }
    }
}
