//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockManagement.Language {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GoodsImport {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GoodsImport() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StockManagement.Language.GoodsImport.GoodsImport", typeof(GoodsImport).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Goods Imports.
        /// </summary>
        public static string goodsImports {
            get {
                return ResourceManager.GetString("goodsImports", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Goods Import Document.
        /// </summary>
        public static string goodsImportDocument {
            get {
                return ResourceManager.GetString("goodsImportDocument", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Create Goods Import Document.
        /// </summary>
        public static string createGoodsImportDocument {
            get {
                return ResourceManager.GetString("createGoodsImportDocument", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Goods import document {0} saved..
        /// </summary>
        public static string goodsImportDocumentSavedToast {
            get {
                return ResourceManager.GetString("goodsImportDocumentSavedToast", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Proforma Number.
        /// </summary>
        public static string proformaNumber {
            get {
                return ResourceManager.GetString("proformaNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Proforma number is required..
        /// </summary>
        public static string proformaNumberRequired {
            get {
                return ResourceManager.GetString("proformaNumberRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A goods import document with this proforma number already exists:.
        /// </summary>
        public static string proformaNumberAlreadyExists {
            get {
                return ResourceManager.GetString("proformaNumberAlreadyExists", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Supplier is required..
        /// </summary>
        public static string supplierRequired {
            get {
                return ResourceManager.GetString("supplierRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Supplier not found..
        /// </summary>
        public static string supplierNotFound {
            get {
                return ResourceManager.GetString("supplierNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select Supplier:.
        /// </summary>
        public static string selectSupplier {
            get {
                return ResourceManager.GetString("selectSupplier", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Incoterm.
        /// </summary>
        public static string incoterm {
            get {
                return ResourceManager.GetString("incoterm", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Incoterm is invalid..
        /// </summary>
        public static string incotermInvalid {
            get {
                return ResourceManager.GetString("incotermInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Broker Name.
        /// </summary>
        public static string brokerName {
            get {
                return ResourceManager.GetString("brokerName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Broker name is required..
        /// </summary>
        public static string brokerNameRequired {
            get {
                return ResourceManager.GetString("brokerNameRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DUA Reference.
        /// </summary>
        public static string duaReference {
            get {
                return ResourceManager.GetString("duaReference", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DUA reference is required..
        /// </summary>
        public static string duaReferenceRequired {
            get {
                return ResourceManager.GetString("duaReferenceRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Document ID.
        /// </summary>
        public static string documentId {
            get {
                return ResourceManager.GetString("documentId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string documentDate {
            get {
                return ResourceManager.GetString("documentDate", resourceCulture);
            }
        }
    }
}
